### ISSUE TITLE
Instructions for running tests locally need to be updated (easy!)

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/Vue-BookListing#22]
**Summary:** For each Module in the course, change the local `npm` test command to instead of `mocha:part` and use `test:module`, e.g., `npm run mocha:part1` :arrow_right:  `npm run test:module1` 

---

**Description:** The top of each part has an outdated `npm` command.  e.g., Module 1's description ([_Creating the BookList Component_](https://app.pluralsight.com/projects/build-a-reading-list-application-with-vue-js/creating-the-booklist-component/5f745137-d457-4c67-88eb-07b39b4618c4)):

<img width="808" alt="screen shot 2018-07-03 at 10 33 13 am" src="https://user-images.githubusercontent.com/5722849/42241012-61253e52-7ec6-11e8-9883-1cb9cef7b8a9.png">

- this was [changed](https://github.com/pluralsight-projects/Vue-BookListing/commit/e192597ca92e42838e0187ff11f792459afea953#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) after the course first came out

**Fix:**

- For any `npm run` command, change its `mocha:part` to `test:module`. 
  e.g., `npm run mocha:part1` :arrow_right:  `npm run test:module1` 
- needs to be changed for each Module

@jonfriskics

**Comment by jonfriskics** [comment]
done.
