### ISSUE TITLE
package.json test commands do not work on Windows

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/Vue-BookListing#23]
**Summary:** The `npm` test commands in package.json don't use `cross-env`.  Use `cross-env` so they work on Windows as well.

Probably fairly easy to fix

---

**Description:** The given `npm test` commands in [package.json](https://github.com/pluralsight-projects/Vue-BookListing/blob/master/package.json) aren't compatible with Windows, and only work on os x (and likely other Linux/BSD/Unix-y systems :smile: ). 

**Fix:**

- `cross-env` will already be installed as it's in package.json, and you just need to precede each `test:` command in package.json with a call to `cross-env`.
- e.g., https://github.com/pluralsight-projects/Vue-BookListing/pull/21/commits/a7a567539aac9a372008bbb7eea68408ede59a29
- This was reported by @mario-d-s.
- I did test out the changes locally on os x, and they were there as well.

@jonfriskics

**Comment by mario-d-s** [comment]
Please see #24.

**Comment by stanggt3** [comment]
Thanks!!
